Support for bazel buildsystem
ignitionrobotics/ign-rendering pull request #179
Opened 2020-11-24 21:12 UTC by mjcarroll

2020-11-26 00:29 UTC, JShep1 reviewed
Initial pass, but can't test with cmake yet due to the `ign_plugin` having a failing build.  All looks good on the bazel side, I'm having one failing test: `RenderingIFace_TEST.cc`.  Looks like it's due to an undefined symbol in `libignition-rendering-ogre2.so`: `FT_Init_FreeType`

2020-12-02 21:20 UTC, JShep1 commented
> Initial pass, but can't test with cmake yet due to the `ign_plugin` having a failing build. All looks good on the bazel side, I'm having one failing test: `RenderingIFace_TEST.cc`. Looks like it's due to an undefined symbol in `libignition-rendering-ogre2.so`: `FT_Init_FreeType`

For the record, I replicated this issue on my desktop running Bionic

2021-04-15 18:27 UTC, mahiuchun requested changes
The latest commit fails to build for me.

```
ign_rendering/ogre2/src/Ogre2DepthCamera.cc:41:10: fatal error: Ogre2ParticleNoiseListener.hh: No such file or directory
 #include "Ogre2ParticleNoiseListener.hh"
```

2021-08-17 00:53 UTC, chapulina requested changes
CI is unhappy

2021-08-17 00:53 UTC, chapulina commented on examples/ogre2_demo/Main.cc
> +    common::joinPaths(std::string("ign_rendering/examples/ogre2_demo"), "media");
This assumes the user is running the example from some specific directory

2021-08-17 00:53 UTC, chapulina commented on include/ignition/rendering/RenderPassSystem.hh
> +#define IGN_RENDERING_REGISTER_RENDER_PASS(classname, interface) \
This move doesn't seem backwards-compatible

2021-11-12 18:01 UTC, chapulina commented
I believe this PR is outdated and not being worked on. Please reopen if this starts being worked on again.

2021-11-12 18:01 UTC, closed without merging