3 ➡️ 4
ignitionrobotics/ign-rendering pull request #270
Opened 2021-03-12 06:23 UTC by chapulina

# ➡️ Forward port

Port `ign-rendering3` to `ign-rendering4`

Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/ign-rendering4...ign-rendering3

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

2021-03-12 07:33 UTC, ahcorde requested changes
GPU rays tests is failing

2021-03-13 09:24 UTC, iche033 commented
gpu rays test is fixed after merging with `ign-rendering4`.

Potential fix for DepthGaussianNoise test in https://github.com/ignitionrobotics/ign-rendering/pull/271

2021-03-13 09:25 UTC, iche033 approved these changes

2021-03-15 19:37 UTC, chapulina commented
> Potential fix for DepthGaussianNoise test 

Thanks. I'll wait for #271 to get in and then update this PR.

2021-03-17 18:31 UTC, merged