Added command line argument for examples to pick version of Ogre
ignitionrobotics/ign-rendering pull request #277
Opened 2021-03-23 19:36 UTC by WilliamLewww

Updated the following examples to use a command line argument to determine which version of Ogre to use (Ogre1 vs. Ogre2):

- actor_animation
- camera_tracking
- custom_scene_viewer
- gazebo_scene_viewer
- lidar_visual
- mesh_viewer
- mouse_picking
- particles_demo
- render_pass
- simple_demo
- thermal_camera
- transform_control
- view_control

2021-03-23 19:55 UTC, ahcorde approved these changes

2021-03-23 19:56 UTC, ahcorde requested changes
Do you mind to sign the commit ? https://github.com/ignitionrobotics/ign-rendering/pull/277/checks?check_run_id=2178517512

2021-03-23 20:48 UTC, WilliamLewww commented
Sorry about, I believe I just signed the commit. I have also configured my GPG key so I think my future commits should contain my signature now.

2021-03-23 20:55 UTC, ahcorde approved these changes

2021-03-23 22:13 UTC, iche033 commented
looks good to me. Just waiting for CI to finish

2021-03-31 03:16 UTC, iche033 approved these changes

2021-03-31 03:16 UTC, merged