Helper function to get a scene
ignitionrobotics/ign-rendering pull request #320
Opened 2021-05-08 00:43 UTC by chapulina

# 🎉 New feature

## Summary

Most applications will only have one rendering engine loaded at a time, and only one scene within that. This helper function gets the first scene that can be found in any rendering engine.

This pattern is being repeated on several `ign-gui` and `ign-gazebo` plugins, so it would be nice to reduce duplication. For example:

* [Screenshot](https://github.com/ignitionrobotics/ign-gui/blob/ffbdb26ce519f85b273d57527a11470dae3838e1/src/plugins/screenshot/Screenshot.cc#L184-L229)
* [Grid3D](https://github.com/ignitionrobotics/ign-gazebo/blob/f795b657683f629133e7de056771959786a150fd/src/gui/plugins/grid_config/GridConfig.cc#L152-L187)
* [VisualizeLidar](https://github.com/ignitionrobotics/ign-gazebo/blob/a41cf80049c07977079d0b215398dc4225b63038/src/gui/plugins/visualize_lidar/VisualizeLidar.cc#L151-L186)
* etc

## Test it

Take a look at the added tests.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

2021-05-10 07:41 UTC, ahcorde requested changes
LGTM, just one minor comment, what do you think about use another name for the method? `getFirstInitializedScene` ?

I can see an error in windows 

```bash
47: [31m[Err] [C:\Jenkins\workspace\ign_rendering-pr-win\ws\ign-rendering\src\RenderEngineManager.cc:336] [m[31mInvalid render-engine index: [m[31m1000000[m[31m
47: [m[       OK ] RenderingIfaceTest.RegisterEngine (67 ms)
```

2021-05-10 17:00 UTC, chapulina commented
> what do you think about use another name for the method? getFirstInitializedScene ?

I  don't know if that name would be necessarily true for the current implementation. For example:

1. Register engine EA
2. Register engine EB
3. Create scene on SB on EB
4. Create scene on SA on EA

SB was initialized before SA, but we'll return SA. Moreover, if we don't do step 4, we will return null.

2021-05-12 07:26 UTC, ahcorde commented
@osrf-jenkins retest this please

2021-05-12 07:27 UTC, ahcorde approved these changes

2021-05-12 18:20 UTC, iche033 commented
> I don't know if that name would be necessarily true for the current implementation.

How about `getFirstRenderEngineScene` to be more specific?

2021-05-12 19:10 UTC, chapulina commented
> How about getFirstRenderEngineScene to be more specific

The trick is whether the "first" applies to the render engine, to the scene, or to both...

I don't have a better suggestion though. I can go with that if you think there isn't a lot of ambiguity. I'd just drop the `get`.

2021-05-12 19:50 UTC, iche033 commented
`sceneFromFirstRenderEngine`? 

I think either one works

2021-05-14 22:13 UTC, chapulina commented
> sceneFromFirstRenderEngine?

Ok, I went with that: e19bd7353d94552db111704f621c4efe627fda95

2021-05-14 22:16 UTC, chapulina commented
> Once this has been reviewed I can rebase and target 3.

Done, this is now targeted at v3

2021-05-14 23:37 UTC, iche033 approved these changes
looks good to me.

2021-05-15 00:59 UTC, merged