Ports/3 to 4 25 may2021
ignitionrobotics/ign-rendering pull request #328
Opened 2021-05-25 16:59 UTC by mjcarroll

# ➡️ Forward port

Port ign-rendering3 to ign-rendering4

Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/ign-rendering4...ign-rendering3

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

2021-05-25 19:08 UTC, ahcorde requested changes
Many MACOS tests are failing https://build.osrfoundation.org/job/ignition_rendering-ci-pr_any-homebrew-amd64/1490/

DCO is failing too

2021-05-27 13:01 UTC, mjcarroll commented
@osrf-jenkins retest this please

2021-05-27 13:35 UTC, mjcarroll commented
> DCO is failing too

I've always had issues with DCO on forward ports

2021-05-27 15:42 UTC, ahcorde approved these changes

2021-05-27 15:42 UTC, merged