Merge main branch into Ogre 2.2 and fixes
ignitionrobotics/ign-rendering pull request #359
Opened 2021-07-03 21:11 UTC by darksylinc

# 🦟 Bug fix

 - Merged main branch into Ogre 2.2 branch
     - Rather do this now than later, while I still have fresh in my mind the code written for the main branch
 - Restored FSAA (this bug affected main branch as well, but another minor bug in 2.2 branch prevented the fixes from main branch from working). Also went for explicit resolve route which was planned from the start, so that VRAM saving feature could be implemented.
 - Save VRAM if FSAA is used + no postprocessing. This optimization is exclusive to Ogre 2.2+
     - This feature deprecates another overload of `UpdateRenderPassChain`
 - Fix bug where changing background colour would not take immediate effect unless the compositor was rebuilt. See changes to `Ogre2RenderTarget::UpdateBackgroundColor`
 - Removed Clear plasses in favour of LoadActions, which are more efficient in modern GPUs

**I apologize for this monolith of a PR. There were many fixes and improvements to implement which relied on merging main -> 2.2 and this merge causes too many conflicts to easily split this into multiple smaller PRs.**

**All ign-rendering tests are _passing_.**

## Summary

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-07-05 09:00 UTC, ahcorde requested changes

2021-07-05 09:00 UTC, ahcorde commented on ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
> +          bool _recreateNodes);
can we remove this ? This PR is targeting ign-rendering6

2021-07-05 09:00 UTC, ahcorde commented on ogre2/include/ignition/rendering/ogre2/Ogre2RenderTarget.hh
> +      protected: IGN_DEPRECATED(5) Ogre::TextureGpu * ogreTexture = nullptr;
can we remove this ? This PR is targeting ign-rendering6

2021-07-05 09:00 UTC, ahcorde commented on ogre2/src/Ogre2DepthCamera.cc
> +  for( size_t i = 0u; i < 2u; ++i )
```suggestion
  for (size_t i = 0u; i < 2u; ++i)
```

2021-07-05 21:34 UTC, darksylinc commented
I've updated the PR with the suggested changes and removed code deprecated for ign-rendering5.

Now DCO bot says my tweets are unverified though Github disagrees; DCO bot is expecting me to use my github handle as username, for some reason

2021-07-06 07:11 UTC, iche033 reviewed
Did some quick tests with a few worlds in ign-gazebo and seems to be working fine.

The `ogre2_demo` couldn't start though. I'm getting:

```
terminate called after throwing an instance of 'Ogre::InvalidParametersException'
  what():  OGRE EXCEPTION(2:InvalidParametersException): RenderTexture 'scene::RenderTexture(65435)0' must be resident! in GL3PlusRenderPassDescriptor::updateColourFbo at /home/osrf/code/ign-ogre_ws/src/ogre-next/RenderSystems/GL3Plus/src/OgreGL3PlusRenderPassDescriptor.cpp (line 223)
Aborted (core dumped)
```

2021-07-10 21:58 UTC, darksylinc commented
> Did some quick tests with a few worlds in ign-gazebo and seems to be working fine.
> 
> The `ogre2_demo` couldn't start though. I'm getting:
> 
> ```
> terminate called after throwing an instance of 'Ogre::InvalidParametersException'
>   what():  OGRE EXCEPTION(2:InvalidParametersException): RenderTexture 'scene::RenderTexture(65435)0' must be resident! in GL3PlusRenderPassDescriptor::updateColourFbo at /home/osrf/code/ign-ogre_ws/src/ogre-next/RenderSystems/GL3Plus/src/OgreGL3PlusRenderPassDescriptor.cpp (line 223)
> Aborted (core dumped)
> ```

Fixed. That slipped through my testing. I had to undo the VRAM saving code (reasons explained in the commit). It's just too much over-engineering to be worth it.

I thought it'd be easier as in, just flip a texture off and reroute a few nodes.

2021-07-12 22:17 UTC, iche033 approved these changes
works well for me now! I think windows CI is not yet working for ogre 2.2. Otherwise, other builds look good.

2021-07-13 07:33 UTC, ahcorde approved these changes

2021-07-13 07:36 UTC, merged