Use selection buffer in ray queries (ogre2)
ignitionrobotics/ign-rendering pull request #378
Opened 2021-08-12 20:43 UTC by iche033

# 🎉 New feature

* requires 

Replaces part of ray query logic with the use of selection buffer (mouse picking) for performance improvement.

The current ray query implementation has 2 stages:
1. ray-bounding box check - broad phase check to narrow down the number of objects that are potentially clicked by the mouse
2. ray-triangle intersection test - checks against all objects found in 1 and compute the actual 3d intersection point on the mesh.

These 2 stages are all done on the CPU and they can be slow if the user clicks on a region with multiple overlapping bounding boxes. This PR replaces stage 1 with the use of selection buffer which can efficiently return the first object that the user clicks on. So that in stage 2 we would only need to do ray intersection test with 1 mesh.

## Test it

Use ign-gazebo, insert multiple overlapping complex meshes, and try panning with the mouse by left clicking on a mesh in the scene and dragging the mouse. The movement should be less laggy with these changes

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-08-19 07:08 UTC, ahcorde requested changes

2021-08-19 07:08 UTC, ahcorde commented on ogre2/src/Ogre2RayQuery.cc
> +  public: Ogre2CameraPtr camera;
```suggestion
  public: Ogre2CameraPtr camera{nullptr};
```

2021-08-19 07:08 UTC, ahcorde commented on ogre2/src/Ogre2RayQuery.cc
> +  public: math::Vector2i imgPos;
```suggestion
  public: math::Vector2i imgPos = math::Vector2i::Zero;
```

2021-08-19 18:39 UTC, iche033 commented on ogre2/src/Ogre2RayQuery.cc
> +  public: math::Vector2i imgPos;
50aefa72c1ed556b718bedd9f88491c2aea55cf1

2021-08-19 18:39 UTC, iche033 commented on ogre2/src/Ogre2RayQuery.cc
> +  public: Ogre2CameraPtr camera;
50aefa72c1ed556b718bedd9f88491c2aea55cf1

2021-09-03 23:45 UTC, iche033 commented
the `UNIT_Utils_TEST` failure is fixed in part 2, #383

2021-09-14 20:29 UTC, nkoenig approved these changes

2021-09-15 07:23 UTC, ahcorde approved these changes
just a minor comment

2021-09-15 07:23 UTC, ahcorde commented on ogre2/src/media/materials/scripts/selection_buffer.material
> +//      fog_override true
remove ?

2021-09-15 18:05 UTC, iche033 commented on ogre2/src/media/materials/scripts/selection_buffer.material
> +//      fog_override true
removed. 72bea5e

2021-09-15 19:40 UTC, merged