Fix loading grayscale emissive map
ignitionrobotics/ign-rendering pull request #503
Opened 2021-12-04 06:51 UTC by iche033

# 🦟 Bug fix

Fixes #499 

## Summary

Continuing the effort from #501, this PR fixes loading grayscale emissive map by converting it to RGB color texture so that the visual with the emissive map is not incorrectly rendered as red color.

Test by lauching ign gazebo with the `fuel_textured_mesh.sdf` world file.

Before:

![tube_grayscale_emissive_before](https://user-images.githubusercontent.com/4000684/144700400-46f18581-1d62-4e6e-9d00-72d1f08547e3.png)

After:

![tube_grayscale_emissive_after](https://user-images.githubusercontent.com/4000684/144700404-619433b7-f2b2-48aa-aa86-5d22ecc9eb8c.png)

## Alternative considered

The other option considered is to some customization in the Pbs Hlms pixel shader and just apply only the r channel of the emissive texture to the final color, .e.g. [changing the code here](https://github.com/ignitionrobotics/ign-rendering/blob/ign-rendering6/ogre2/src/media/Hlms/Pbs/Any/Main/800.PixelShader_piece_ps.any#L521) to `finalColour += emissiveCol.rrr;`. 

I went with the approach in this PR mainly to keep the changes within one function without touching the shaders so we don't deviate too much from the original Pbs shader code we took from ogre. This approach was also easier for me to to implement.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-12-04 19:13 UTC, ahcorde requested changes

2021-12-04 19:13 UTC, ahcorde commented on ogre2/src/Ogre2Material.cc
> +            << rgbTexName << std::endl;
```suggestion
        ignmsg << "Grayscale emissive texture detected. Converting to RGB: "
               << rgbTexName << std::endl;
```

2021-12-04 19:13 UTC, ahcorde commented on ogre2/src/Ogre2Material.cc
> +      std::string p = common::parentPath(_texture);
```suggestion
      std::string parentDirectory = common::parentPath(_texture);
```
more descriptive name?

2021-12-04 22:03 UTC, darksylinc commented
Sounds like this is something that should be fixed from Upstream.

Detect if emissive is greyscale, then use a shader with the right swizzle

2021-12-06 23:37 UTC, iche033 commented on ogre2/src/Ogre2Material.cc
> +      std::string p = common::parentPath(_texture);
a6796ac

2021-12-06 23:37 UTC, iche033 commented on ogre2/src/Ogre2Material.cc
> +            << rgbTexName << std::endl;
a6796ac

2021-12-06 23:41 UTC, iche033 commented
great, thanks for implementing grayscale emissive map support upstream! I'm going to try get this in first, and remove later when I get time to port the fix over to our fork (and package / release new debs etc)

2021-12-07 15:02 UTC, ahcorde approved these changes

2021-12-07 19:19 UTC, merged