Fix material switching for objects using shaders (ogre2)
ignitionrobotics/ign-rendering pull request #533
Opened 2022-01-08 00:14 UTC by iche033

# 🦟 Bug fix

## Summary

Mouse picking works by assigning a unique material to an object. When a user clicks on a object, we switch out its material to a unique one to identify the clicked object. There is bug that when switching objects that use custom shader materials. Added an extra check and logic make sure we restore the correct material (low level shader material).

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-01-12 08:49 UTC, ahcorde requested changes
can we add a test ?

2022-01-13 00:24 UTC, iche033 commented
> can we add a test ?

yep, added test in 33dd4c4

2022-01-13 05:06 UTC, iche033 commented
hmm test is failing on github bionic build but pass on focal and other jenkins machines. Not sure if it's a bionic software rendering or mesa driver issue or something else. Added logic to disable test on github action. f82a0ac

2022-01-17 09:57 UTC, ahcorde approved these changes
some minor style issues

2022-01-17 09:57 UTC, ahcorde commented on test/integration/camera.cc
> +            << _renderEngine << std::endl;
```suggestion
           << _renderEngine << std::endl;
```

2022-01-17 09:57 UTC, ahcorde commented on test/integration/camera.cc
> +              << "' is not supported" << std::endl;
```suggestion
    igndbg << "Engine '" << _renderEngine
           << "' is not supported" << std::endl;
```

2022-01-18 19:07 UTC, iche033 commented on test/integration/camera.cc
> +              << "' is not supported" << std::endl;
dc5211e17560836ddc900ea4fabb8047d55ad6f9

2022-01-18 19:07 UTC, iche033 commented on test/integration/camera.cc
> +            << _renderEngine << std::endl;
dc5211e17560836ddc900ea4fabb8047d55ad6f9

2022-01-18 19:08 UTC, ahcorde approved these changes

2022-01-18 19:49 UTC, merged

2022-03-01 18:30 UTC, osrf-triage commented
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-01-citadel-edifice-fortress/1313/1